services:
  db:
    image: postgres:15-alpine
    container_name: ged_postgres
    restart: always
    environment:
      POSTGRES_DB: ged_db
      POSTGRES_USER: administrator
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: ged-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/ged-documents;
      /usr/bin/mc anonymous set public myminio/ged-documents;
      exit 0;
      "

volumes:
  postgres_data:
  minio_data: