spring.datasource.url=jdbc:postgresql://localhost:5432/ged_db
spring.datasource.username=administrator
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.user=administrator
spring.flyway.password=admin123


# Remova as linhas duplicadas e use apenas as referências às variáveis
storage.s3.endpoint=${STORAGE_S3_ENDPOINT}
storage.s3.region=${STORAGE_S3_REGION}
storage.s3.access-key=${STORAGE_S3_ACCESS_KEY}
storage.s3.secret-key=${STORAGE_S3_SECRET_KEY}
storage.s3.bucket-name=${STORAGE_S3_BUCKET_NAME}