spring.datasource.url=jdbc:postgresql://localhost:5432/ged_db
spring.datasource.username=administrator
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.user=administrator
spring.flyway.password=admin123