# Configurações de Storage (Supabase S3)
storage.s3.endpoint=${STORAGE_S3_ENDPOINT}
storage.s3.region=${STORAGE_S3_REGION}
storage.s3.access-key=${STORAGE_S3_ACCESS_KEY}
storage.s3.secret-key=${STORAGE_S3_SECRET_KEY}
storage.s3.bucket-name=documents

# Configurações de Banco (JDBC padrão)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.user=${SPRING_DATASOURCE_USERNAME}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD}