package com.dhensouza.ged.domain.enums;

public enum AuditAction {
    DOCUMENT_CREATED,
    DOCUMENT_UPDATED,
    DOCUMENT_PUBLISHED,
    DOCUMENT_ARCHIVED,
    FILE_UPLOADED,
    FILE_DOWNLOADED,
    CREATE_DOCUMENT,
    UPDATE_DOCUMENT,
    DELETE_DOCUMENT,
    VIEW_DOCUMENT,
    UPLOAD_VERSION,
    DOWNLOAD_FILE,
    LOGIN_SUCCESS,
    LOGIN_FAILURE
}
