name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Wait for Postgres to be ready
        run: |
          until docker exec ged_postgres pg_isready ; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Build and Test with Maven
        run: ./mvnw test -Ptest